cloud:
  aws:
    credentials:
      access-key: AKIA5GC5QD3XK37F5AAU
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: florezy


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080